backend:
  name: git-gateway
  branch: main
publish_mode: editorial_workflow
media_folder: "public/assets/uploads"
public_folder: "/assets/uploads"
collections:
  # Logo Projects
  - name: "logo"
    label: "Logo Projects"
    folder: "src/logoprojects"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Tags", name: "tags", widget: "list", default: ["logo"] }
      - { label: "Featured Image", name: "image", widget: "image" }

  # Graphic Projects
  - name: "graphic"
    label: "Graphic Projects"
    folder: "src/graphicprojects"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Tags", name: "tags", widget: "list", default: ["graphic"] }
      - { label: "Featured Image", name: "image", widget: "image" }

  # Services
  - name: "service"
    label: "Services"
    folder: "src/service"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Tags", name: "tags", widget: "list", default: ["service"] }
      - { label: "First Part of Title", name: "title1", widget: "string" }
      - { label: "Second Part of Title", name: "title2", widget: "string" }
      - { label: "1stLine", name: "1stLine", widget: "string" }
      - { label: "2ndLine", name: "2ndLine", widget: "string" }
      - { label: "3rdLine", name: "3rdLine", widget: "string" }
      - { label: "4thLine", name: "4thLine", widget: "string" }

  # Portfolio Widget
  - name: "portfolioWidget"
    label: "Portfolio Widget"
    folder: "src/portfolioWidget"
    create: true
    slug: "{{slug}}"
    fields:
      - {
          label: "Tags",
          name: "tags",
          widget: "list",
          default: ["portfolioWidget"],
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Featured Image", name: "image", widget: "image" }
      - { label: "Linked Page", name: "link", widget: "string" }

  # About Me
  - name: "aboutme"
    label: "About Me"
    folder: "src/aboutme"
    create: false
    slug: "{{slug}}"
    fields:
      - { label: "Featured Image", name: "image", widget: "image" }
      - { label: "Featured PDF", name: "pdf", widget: "file" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Years experience", name: "yearsExperience", widget: "string" }
      - {
          label: "Completed project",
          name: "completedProjects",
          widget: "string",
        }
      - { label: "Companies worked", name: "companiesWorked", widget: "string" }
      - { label: "Tags", name: "tags", widget: "list", default: ["aboutme"] }
